### ISSUE TITLE
将二维码扫描界面打开，手机放置在桌上，屏幕向上，会出现扫描出结果的效果

### ISSUE THREAD

**Issue by usherjc** [bingoogolapple/BGAQRCode-Android#103]
如题，当手机打开二维码扫描界面放置在桌上的时候，我是做了一个扫描成功后显示出扫描结果的dialog，然后当手机屏幕向上，摄像头向下的时候，会出现偶发性的扫描成功的结果，出现一大串数字，求解

**Comment by zbcloading** [comment]
我也是，偶尔会出现一串数字

**Comment by HelloLollipop** [comment]
@zbcloading 我把扫描框控制为那个对准框的时候，这种情况就没有出现过了

**Comment by HelloLollipop** [comment]
扫描框控制为那个对准框的时候，这种情况又出现了

**Comment by bingoogolapple** [comment]
用最新版
