### ISSUE TITLE
不把二维码放在预览的小框中也会自动对焦并识别出结果

### ISSUE THREAD

**Issue by HelloLollipop** [bingoogolapple/BGAQRCode-Android#104]
不把二维码放在预览的小框中也会自动对焦并识别出结果，用预览界面的非对准框出也会自动对焦识别

**Comment by bingoogolapple** [comment]
对焦这个不改了，未对准扫描框也能识别出结果这个问题在配置文件中设置「qrcv_isOnlyDecodeScanBoxArea」为「true」，建议先把「README」中的「自定义属性说明」看了

**Comment by HelloLollipop** [comment]
收到
