### ISSUE TITLE
二维码和条码在一起，打开扫条码，但是几乎扫到的都是二维码？

### ISSUE THREAD

**Issue by changjiashuai** [bingoogolapple/BGAQRCode-Android#105]
![20170118_143251](https://cloud.githubusercontent.com/assets/4496625/22054045/d67710ac-dd8e-11e6-98a6-7c3734ecb6a3.jpg)

qrcv_isOnlyDecodeScanBoxArea 这个属性不管用？？？

**Comment by bingoogolapple** [comment]
试试最新版

**Comment by bingoogolapple** [comment]
指定只识别扫描框区域
