### ISSUE TITLE
在二维码内容比多的情况下，有很大的几率会将内容错误的识别成某段数字串（不同机型概率不一样）

### ISSUE THREAD

**Issue by LeefMagnet** [bingoogolapple/BGAQRCode-Android#107]
这个情况在华为Mate 9 Pro 下错误识别称错误数字串的概率比较高，用三星、魅族和其他的也会出现，但是出错的几率比较低。请问能帮助解决一下吗？

**Comment by GitACDreamer** [comment]
ZXing 识别一维码也是，只要是一维码比较密集，比如20位的字母加数字，，经常得到的结果是8位数的数字，我用的是Honor 8

**Comment by bingoogolapple** [comment]
用最新版
