### ISSUE TITLE
zxing 不能扫描条形码么

### ISSUE THREAD

**Issue by JiangRuCi** [bingoogolapple/BGAQRCode-Android#11]
zxing扫描条形码的成功率几乎为0

**Comment by bingoogolapple** [comment]
![image](https://cloud.githubusercontent.com/assets/8949716/15790201/a21a9b34-2a02-11e6-964c-20533e280d27.png)

@JiangRuCi 我试了一下截图里所有类型的条形码，除了红色方框里那五种不能扫描，其余的都可以扫描出来

**Comment by bingoogolapple** [comment]
横屏扫描用 v1.1.8 版本
