### ISSUE TITLE
import module zxingdemo出现cn.bingoogolapple.photopicker.activity.BGAPhotoPickerActivity not exists

### ISSUE THREAD

**Issue by ballgi** [bingoogolapple/BGAQRCode-Android#112]
我试著import qrcodecore,zxing,zxingdemo
试著把zxingdemo TestScanAcitivty.java copy to 自建的mainAcitivty
但import cn.bingoogolapple.photopicker.activity.BGAPhotoPickerActivity;一直显示不存在
cn.bingoogolapple.photopicker.activity.BGAPhotoPickerActivity not exist

**Comment by yclog** [comment]
这个Activity作用其实图片选择Activity，如果不使用读取操作的话，可以之间删除，同理也可以自己写，从调用处很好理解写出同等效果Activity
