### ISSUE TITLE
Zbar扫描条形码识别必错

### ISSUE THREAD

**Issue by usherjc** [bingoogolapple/BGAQRCode-Android#119]
条形码扫描遗失收首几位数字与尾部数字或扫描结果全部错误

**Comment by HelloLollipop** [comment]
![书本条形码扫描结果](https://cloud.githubusercontent.com/assets/17808551/24088088/449ba2bc-0d61-11e7-838d-7bbe76f1611f.JPG)

- 测试书本类的条形码几乎都是错误的
- 测试其他商品类【如卫生纸条形码】偶发性错误且概率较多

**Comment by liguangze** [comment]
@usherjc   找到解决方案 了吗，我也有这样的问题

**Comment by bingoogolapple** [comment]
升级到最新版
