### ISSUE TITLE
更新了最新的版本，扫描速度变慢。怎么回事？

### ISSUE THREAD

**Issue by laishujie** [bingoogolapple/BGAQRCode-Android#122]

**Comment by zj012611** [comment]
不是慢了，而是识别率低的已经无法使用

**Comment by YeDaxia** [comment]
zxing版本下载了源码编译测试确实非常慢，退到1.1.6版本也是一样，更换zxing版本也没什么效果。

**Comment by YeDaxia** [comment]
补充：下载的demo确实非常快，请作者有空修复一下。

**Comment by yanyusong** [comment]
是啊，我的也是，怎么回事呀

**Comment by supercwn** [comment]
改成zxing_3.2.0好像会稍微的快点

**Comment by 13691525793** [comment]
使用zxing_3.2.1debug的确实很慢,不知道啥原因,打包成release版本的就快了.自己测试的是这样的

**Comment by ThinkingInMe** [comment]
无法识别,为什么demo是可以的

**Comment by cjcj125125** [comment]
确实很慢，求解，哪位有好的第三方麻烦介绍个，感激不尽

**Comment by bingoogolapple** [comment]
参考 #170
