### ISSUE TITLE
博主什么时候能优化下识别率，现在的版本好多手机都扫不出来了

### ISSUE THREAD

**Issue by zj012611** [bingoogolapple/BGAQRCode-Android#123]
识别率现在很低，二维码很多手机都不能识别。。。以前一直用博主牛逼的控件，现在这个版本真的无法使用了，刚好要给客户了，都换成最原始的方式了，卡的一笔啊。。。。。。

**Comment by bingoogolapple** [comment]
升级到最新版，参考 #170
