### ISSUE TITLE
打开扫描，没有扫到二维码，他也不停弹出扫描结果，在华为MATE9 android 7.0

### ISSUE THREAD

**Issue by wublack** [bingoogolapple/BGAQRCode-Android#125]
Zbardemo上，随便扫到哪里都会弹出扫描结果。zxingdemo扫码经常扫不到.

**Comment by haozecc** [comment]
同样遇到这个问题，客户反映mate9扫描不出结果，或者扫描很慢

**Comment by didixyy** [comment]
同这个问题

**Comment by nangonghuang** [comment]
https://github.com/bingoogolapple/BGAQRCode-Android/issues/33

**Comment by XiaYL** [comment]
也是这个问题，一瞬间我以为是我手机坏了

**Comment by scofieldhhl** [comment]
我也遇到这种问题，其他机型手机扫码都是正常，Mate9扫码出来是一串数字，而我的内容是一个URL

**Comment by bingoogolapple** [comment]
用最新版

**Comment by 951AB159BA** [comment]
@bingoogolapple 用1.3.6版本扫不完整的二维码还是出现的
