### ISSUE TITLE
无法自动对焦

### ISSUE THREAD

**Issue by KIDNG** [bingoogolapple/BGAQRCode-Android#135]
感觉应该是代码逻辑问题，`CameraPreview.mSurfaceCreated`一直为false

**Comment by linceln** [comment]
加
<uses-feature android:name="android.hardware.camera"/>
<uses-feature android:name="android.hardware.camera.autofocus"/>

**Comment by linceln** [comment]
```
<uses-feature android:name="android.hardware.camera"/>
<uses-feature android:name="android.hardware.camera.autofocus"/>
``` 
@KIDNG
