### ISSUE TITLE
同样一张二维码图片，通过相机扫码的方式可以识别，通过相册选择图片却识别不到

### ISSUE THREAD

**Issue by sanwuwy** [bingoogolapple/BGAQRCode-Android#141]
![qrcode](https://cloud.githubusercontent.com/assets/11894603/26517864/9210152a-42d4-11e7-9f8c-c165e12897e0.png)

**Comment by Yanqilong** [comment]
同问，我这里也出现了这个问题

**Comment by zhjun2016** [comment]
我的是相反，同一个二维码，从相册扫描很快，用相机扫描特别慢，特别是oppo机型很明显，大神没回答，你们进了大神的群吗

**Comment by bingoogolapple** [comment]
@sanwuwy 手机里的图片原图背景色是不是透明的？

**Comment by Jessiqi** [comment]
同一个二维码，相册里识别不出来
