### ISSUE TITLE
扫描框调整

### ISSUE THREAD

**Issue by ASheng-Bisheng** [bingoogolapple/BGAQRCode-Android#149]
在里面重写的方法中哪一个是可以调整扫描框大小的类？
![image](https://user-images.githubusercontent.com/20983615/27378627-120a261e-56ab-11e7-9f7d-093b030836f6.png)这个类中我都没有看到你设置的扫描框的大小

**Comment by bingoogolapple** [comment]
看文档里自定义属性说明
