### ISSUE TITLE
请求权限用户同意后，开启相机预览识别黑屏

### ISSUE THREAD

**Issue by DywaneQ** [bingoogolapple/BGAQRCode-Android#152]
请求权限允许回调中调用startSpot()无法开启预览

**Comment by Chowing** [comment]
同问

**Comment by superzhangbao** [comment]
同问

**Comment by Qin0821** [comment]
同样的问题，通过和demo一样，在前一个activity中申请权限，通过后再进入二维码扫描界面即可

**Comment by bingoogolapple** [comment]
在自己项目里集成时记得在 onDestroy 方法中调用 mQRCodeView.onDestroy() 释放资源，不然会出现黑屏
