### ISSUE TITLE
demo里怎么没有生成二维码的例子

### ISSUE THREAD

**Issue by superzhangbao** [bingoogolapple/BGAQRCode-Android#161]
求一个生成二维码的demo

**Comment by bingoogolapple** [comment]
https://github.com/bingoogolapple/BGAQRCode-Android/blob/master/zxingdemo/src/main/java/cn/bingoogolapple/qrcode/zxingdemo/TestGeneratectivity.java

**Comment by superzhangbao** [comment]
这个页面上的二维码是生成的啊,我还以为是固定的,展示解析二维码内容的呢.哈哈  谢谢啦
