### ISSUE TITLE
感觉bug太多作者要抛弃这个库跑路了...

### ISSUE THREAD

**Issue by HelloLollipop** [bingoogolapple/BGAQRCode-Android#165]
已经把项目里关于这个库的代码全部删除...

**Comment by CaoyangLee** [comment]
刚想要用...没想到那么多bug 然后第二个ZBar的依赖竟然不可用~

**Comment by bingoogolapple** [comment]
最近在忙公司的事情。@HelloLollipop 你可以自己依赖源码来研究改的，也不用一直当伸手党吧

**Comment by xiang473535976** [comment]
希望楼主继续维护   加快扫描速度…………      谢谢

**Comment by xiang473535976** [comment]
希望楼主继续维护 加快扫描速度………… 谢谢 @bingoogolapple

**Comment by HelloLollipop** [comment]
已经弃坑，你这个不是外部的闪退异常，扫描结果出错，这个问题属于软问题，微信的二维码功能是20个人在做，这种问题外部没办法解决。

**Comment by hudan2714** [comment]
是不是没人管了？
