### ISSUE TITLE
防混淆

### ISSUE THREAD

**Issue by loonggg** [bingoogolapple/BGAQRCode-Android#17]
应该加一个防混淆的说明。

**Comment by lvtanxi** [comment]
用的zbar就加-keep class net.sourceforge.zbar.{*;}
用zxing就加-keep class com.google.zxing.{; }
-dontwarn com.google.zxing.*
如果还有问题的话就加
-dontwarn cn.bingoogolapple.**
-keep class cn.bingoogolapple.*{;}

**Comment by Steamed** [comment]
还是会报错啊
