### ISSUE TITLE
识别率不高的原因找到了！

### ISSUE THREAD

**Issue by ainiyou** [bingoogolapple/BGAQRCode-Android#170]
demo代码copy至项目中，但是识别率一直很低，聚焦不明显，百思不得其解，终于发现demo的gradle版本为2.14.1，而我使用的gradle版本为3.3，经过测试确实如此，望作者有空改改吧

**Comment by vihuela** [comment]
我也测试过了，确实如题主所说，gradle改成，2.14.1，根目录的build版本改成， classpath 'com.android.tools.build:gradle:2.2.3'即可解决

**Comment by dwh178659824** [comment]
根本原因并不是gradle版本问题，而是Instant Run，开启Instant Run运行出来的项目，二维码识别很慢，关闭Instant Run再运行即可正常，而正好gradle 2.2.3默认是不使用Instant Run运行的

**Comment by chaiyingmin** [comment]
我关了Instant Run 也还是一般，扫手机支付码还是可以的，扫商品条码就差了一些，，给客户用的呀  这个不能这样，我能做什么改进一下呢

**Comment by shengguan** [comment]
@ainiyou 为什么我试了没有用

**Comment by EpicWang** [comment]
@dwh178659824 正解

**Comment by JoinBelieve** [comment]
关了Instant Run 貌似没有用呀

**Comment by summertravel** [comment]
同一发布包，低端机型上腾讯加固后的包比加固前识别速度慢很多

**Comment by alen252** [comment]
@dwh178659824 正解 感谢

**Comment by ILoveLin** [comment]
> 根本原因并不是gradle版本问题，而是Instant Run，开启Instant Run运行出来的项目，二维码识别很慢，关闭Instant Run再运行即可正常，而正好gradle 2.2.3默认是不使用Instant Run运行的

确实有用~~~~记得关闭Instant Run,AndroidStudio 4.0版本以上Instant Run 改名为HotSwap(热交换)
