### ISSUE TITLE
扫描框之外也能扫描

### ISSUE THREAD

**Issue by wanghongjia** [bingoogolapple/BGAQRCode-Android#173]
扫描框之外的部分也能扫描  如果二维码密集会有问题

**Comment by huhuime** [comment]
我遇到了方框外比方框里识别更快的问题怎么破？

**Comment by bingoogolapple** [comment]
![image](https://user-images.githubusercontent.com/8949716/30529066-0a1a87c6-9c6c-11e7-8dde-dbf2786c498a.png)

**Comment by 951AB159BA** [comment]
这个是严重bug。还没修复么？？
