### ISSUE TITLE
mate9上无法扫描出结果

### ISSUE THREAD

**Issue by hudan2714** [bingoogolapple/BGAQRCode-Android#178]
安装你上面的demo apk在mate9上进行扫描。。。扫描不出来结果。。。两个demo都扫描不出来。。。这确实是个大问题啊。。。好像很多使用者都有同样的问题。。还望作者能解决一下。。。

**Comment by FlyInTheSkyToMe** [comment]
我也遇见这个问题了，请问是怎么解决的？

**Comment by FlyInTheSkyToMe** [comment]
@hudan2714

**Comment by FlyInTheSkyToMe** [comment]
@bingoogolapple

**Comment by FlyInTheSkyToMe** [comment]
我在项目中使用了这个：
compile 'com.google.zxing:core:3.2.1'
compile 'cn.bingoogolapple:bga-qrcodecore:1.1.7@aar'
compile 'cn.bingoogolapple:bga-zxing:1.1.7@aar'

我老板的手机是 华为 Mate 9 Pro  ，  同样的apk， zxing扫一扫其它手机没问题， 暂时发现就这款手机扫码几乎没反应。    please  help  me ！    thank  you  ！

**Comment by bingoogolapple** [comment]
用最新的 1.1.9 试试，再不行的话就依赖源码 debug 看看

**Comment by FlyInTheSkyToMe** [comment]
好的， 等这款手机拿到手的时候，我就试试。到时候告诉你。

**Comment by acgcode** [comment]
请问这个问题解决了吗，我这边客户也是反馈 Mate 9扫不上码

**Comment by FlyInTheSkyToMe** [comment]
1.1.9 的还是这种情况。 debug的话，查找了一下，暂时还没有找到原因。

**Comment by ideastudios** [comment]
把 下面属性设置为ture 亲测没问题
app:qrcv_isOnlyDecodeScanBoxArea="true"

**Comment by FlyInTheSkyToMe** [comment]
@ideastudios thank you ， 我试试。

**Comment by wanghengx** [comment]
加一行这个 结果问题 mQRCodeView.getScanBoxView().setOnlyDecodeScanBoxArea(true);

**Comment by ZhuSky** [comment]
没有用啊  ，mate9pro  也就是 扫不出来，但是用相册中的图片就很快的出来了

**Comment by ZhuSky** [comment]
@FlyInTheSkyToMe 远了也是一样

**Comment by FlyInTheSkyToMe** [comment]
恩， 确实是有一些问题。

**Comment by bingoogolapple** [comment]
用最新版
