### ISSUE TITLE
这个库的混淆规则该如何写？

### ISSUE THREAD

**Issue by izhijian** [bingoogolapple/BGAQRCode-Android#18]

**Comment by lvtanxi** [comment]
用的zbar就加-keep class net.sourceforge.zbar.**{*;}
用zxing就加-keep class com.google.zxing.**{*; }
-dontwarn com.google.zxing.**
如果还有问题的话就加
-dontwarn cn.bingoogolapple.**
-keep class cn.bingoogolapple.**{*;}
