### ISSUE TITLE
华为荣耀9扫码过慢或无法识别

### ISSUE THREAD

**Issue by acgcode** [bingoogolapple/BGAQRCode-Android#185]
如题，用的zbar1.1.8和1.1.9的版本都是如此

**Comment by mishaoshuai** [comment]
请问荣耀9扫码无法识别解决了吗，我也遇到了，需要旋转90度才能扫描出来，要不然就不出或者是识别错误

**Comment by bingoogolapple** [comment]
用最新版

**Comment by wukuiqing49** [comment]
1.3.4 版本这个版本依然存在,在高屏幕亮度的情况下 能识别  但是识别率也不是很高.  会不会是手机本身的自动聚焦和相机防抖功能的缺陷问题.
