### ISSUE TITLE
相册界面好丑啊

### ISSUE THREAD

**Issue by hyman-lee** [bingoogolapple/BGAQRCode-Android#186]
为什么不调用系统的相册选择图片，丑也就算了，还用了TestScan的Toolbar，我就把toolbar名字改了下，然后一直用不了，然后adb才发现找不到toolbar。。。。。。。。。为什么这边不开源呢？

**Comment by hyman-lee** [comment]
好吧，原来那个只是用来回去filepath的，直接调用相机的九ok了

**Comment by MirrorFlower** [comment]
我自己写的打开相册 然后拿到了选择的图片的path  为啥还是解析不了？提示：未发现二维码
