### ISSUE TITLE
识别速度很慢

### ISSUE THREAD

**Issue by kllkko** [bingoogolapple/BGAQRCode-Android#192]
某些华为手机如mate9基本无法使用

**Comment by ihewro** [comment]
确实 p10同样是这样的

不知道这个解码速度和什么有关呢？

**Comment by acbsimon** [comment]
我也遇到扫描很慢的问题: 在华为G9上的debug包很慢，基本无法扫描，但是正式版没问题。在华为平板上没有这个问题。

**Comment by Rairmmd** [comment]
乐视手机扫码也非常慢

**Comment by bingoogolapple** [comment]
升级到最新版，参考 #170
