### ISSUE TITLE
华为mate9扫描不到二维码内容 解决方案

### ISSUE THREAD

**Issue by ideastudios** [bingoogolapple/BGAQRCode-Android#194]
把 下面属性设置为ture 亲测没问题
app:qrcv_isOnlyDecodeScanBoxArea="true"

**Comment by ItsDon** [comment]
app:qrcv_isOnlyDecodeScanBoxArea="false" 为什么不可以呢？

**Comment by ItsDon** [comment]
@ideastudios  老铁，是什么原因导致的？

**Comment by ideastudios** [comment]
@ItsDon 我也不知道什么原因

**Comment by Zengyi20160602** [comment]
这个属性定义了是否只解析扫码框框住的部分，设为true的时候就只会解析扫码框内的图片，能提高准确性，为false的时候整个手机屏预览界面内都会解析。

**Comment by szhittech** [comment]
@ideastudios 老铁啊，app:qrcv_isOnlyDecodeScanBoxArea="true"设置了还是不行啊，华为mate9 扫描依然是一串数字，我的二维码原本就是一个url（https://api.clife.cn/v1/account/scanLogin/scanQrcode/0895f8d541734bb880e450b33422631c）

**Comment by ideastudios** [comment]
@szhittech 很不幸 mate9 摄像头坏了 扫描不了了  不过刚选了本地图片 能识别出来你输入的网址 换个姿势？  
![1512533219](https://user-images.githubusercontent.com/16684417/33644130-03e09968-da7e-11e7-846d-2bb55b197565.png)

**Comment by szhittech** [comment]
@ideastudios  你用的是bingoogolapple/BGAQRCode-Android这个里面的demo吗？有QQ吗，能给联系方式吗？

**Comment by ideastudios** [comment]
@szhittech  用的是bingoogolapple/BGAQRCode-Android 里面的zxingdemo  clone下来之后  xml里面 设置app:qrcv_isOnlyDecodeScanBoxArea="true"   用上面那张二维码图 从相册扫描 可以读出扫描到的网址  其他 啥都没改 由于手机摄像头已坏 不能测试直接扫描  建议： 1.运行demo后 看相关log  2.可以看下是否是生成二维码的问题  3 附件为zxing demo apk包 可以安装试试   4.如果还是有问题  我也很绝望
[zxingdemo-debug.zip](https://github.com/bingoogolapple/BGAQRCode-Android/files/1534159/zxingdemo-debug.zip)

**Comment by szhittech** [comment]
@ideastudios 你不是用的zbar呀？我用的zbar

**Comment by bingoogolapple** [comment]
用最新版
