### ISSUE TITLE
請問有人有掃不出正確結果的解決辦法嗎？

### ISSUE THREAD

**Issue by augusWuDotan** [bingoogolapple/BGAQRCode-Android#200]
ex > [洗澡]文字的qrcode圖示 掃出來變成亂碼

**Comment by GoAheadComeOn** [comment]
ZBar 扫描二维码「扫描中文会有乱码，如果对中文有要求，请使用 ZXing」，你看是不是这个问题

**Comment by bingoogolapple** [comment]
implementation 'cn.bingoogolapple:bga-qrcode-zbar:1.2.0'
