### ISSUE TITLE
1.1.9版本无法加载

### ISSUE THREAD

**Issue by hudan2714** [bingoogolapple/BGAQRCode-Android#201]
**android studio 3.0版本**

Unable to resolve dependency for ':NewXia@officialReleaseUnitTest/compileClasspath': Could not resolve cn.bingoogolapple:bga-qrcodecore:1.1.9.

Could not resolve cn.bingoogolapple:bga-qrcodecore:1.1.9.
Required by:
    project :NewXia
 > No cached version of cn.bingoogolapple:bga-qrcodecore:1.1.9 available for offline mode.

**Comment by hudan2714** [comment]
android studio 3.0版本了

**Comment by bingoogolapple** [comment]
zxing 用 implementation 'cn.bingoogolapple:bga-qrcode-zbar:1.2.0'
zbar 用 implementation 'cn.bingoogolapple:bga-qrcode-zxing:1.2.0'
