### ISSUE TITLE
解决zbar中文乱码问题

### ISSUE THREAD

**Issue by songwensw** [bingoogolapple/BGAQRCode-Android#209]
修改qrdectxt.c文件里163行左右，修改utf-8为优先的编码格式
![image](https://user-images.githubusercontent.com/5276830/34087855-bbba1274-e3e0-11e7-98fe-447449e6a77f.png)

**Comment by augusWuDotan** [comment]
請問實際上要在哪裡修改呢？如果我只是compile這個包進我的專案。

**Comment by songwensw** [comment]
需要ndk下修改c代码重新编译。
我有编译好的项目，需要我可以把代码发给你，你使用就包含替换一下就行了

**Comment by augusWuDotan** [comment]
好的謝謝你喔!!!


2017-12-22 11:08 GMT+08:00 songwensw <notifications@github.com>:

**Comment by songwensw** [comment]
@augusWuDotan 留个邮箱

**Comment by augusWuDotan** [comment]
popo124117@gmail.com
感謝大大

2017-12-22 11:22 GMT+08:00 songwensw <notifications@github.com>:

**Comment by bingoogolapple** [comment]
@songwensw 来个 PR

**Comment by allenyulun** [comment]
@songwensw  请问c源码是哪里来的?反编译so文件吗？

**Comment by bingoogolapple** [comment]
implementation 'cn.bingoogolapple:bga-qrcode-zbar:1.2.0'

**Comment by Tomato3351** [comment]
有编译好的吗？  heihuoyi@126.com  谢谢大神！
