### ISSUE TITLE
关于识别率问题

### ISSUE THREAD

**Issue by GoAheadComeOn** [bingoogolapple/BGAQRCode-Android#210]
OPPO的一款手机在同事的显示器（很旧的笔记本）上扫描很慢，或者识别不出来，我让同事把这个二维码截图发给我，在我的显示器（去年的新款）上扫描很快扫描出结果，锤子和其他的手机在两个显示器上都能很快的扫描出结果但是在同事的那台久笔记本上的识别速度回相对慢一些

**Comment by bingoogolapple** [comment]
升级到最新版，参考 #170
