### ISSUE TITLE
扫描速度很慢

### ISSUE THREAD

**Issue by aljian** [bingoogolapple/BGAQRCode-Android#211]
demo跑的扫描速度很快,我把demo的zxingdemo代码CV到自己新建的项目 扫描速度就很慢,这是什么原因呢?

**Comment by mochixuan** [comment]
比手机浏览器慢的不是一点啊，尤其是复杂的二维码，差距太大了，有没有什么参数可以调节的

**Comment by liguangze** [comment]
+1

**Comment by bingoogolapple** [comment]
升级到最新版，参考 #170
