### ISSUE TITLE
zbardemo与zxingdemo有什么区别

### ISSUE THREAD

**Issue by liguangze** [bingoogolapple/BGAQRCode-Android#213]
为什么我用zxingdemo有的条形码就扫不出来，zbardemo,就非常快的出来，zbardemo好像比zxingdemo好很多，他们有什么本质的区别吗，
 compile 'cn.bingoogolapple:bga-qrcodecore:1.1.9@aar'
 compile 'cn.bingoogolapple:bga-zbar:1.1.9@aar'

跟引类库有什么区别，样式我想改下，只能引用类库了
jniLibs里面的东西必须引吗，求大神解答下，谢谢，已经打赏

**Comment by liguangze** [comment]
++++++++++1

**Comment by bingoogolapple** [comment]
zbar c实现，zxing java实现

zbar 必须要 jniLibs 里的东西，建议用最新版，解决了zbar中文乱码问题

**Comment by liguangze** [comment]
@bingoogolapple  谢谢，为什么zbar一般的条形码都能扫出来，zxingdemo就不如zbar好用呢

**Comment by liguangze** [comment]
你好，我的studio是2.3版本的，现在还不想升级，导入您最新的项目总是报错，能给指点下吗

**Comment by allenyulun** [comment]
zbar， so只用 'armeabi'时，是扫不出码的，armeabi的so应该有问题
