### ISSUE TITLE
Zbar，armeabi类型缺少了一个 so

### ISSUE THREAD

**Issue by AzusaL** [bingoogolapple/BGAQRCode-Android#221]
nativeLibraryDirectories=[/data/app/com.coe.dispatchsystem-2/lib/arm, /data/app/com.coe.dispatchsystem-2/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]] couldn't find "libzbarjni.so"
![_20180122134929](https://user-images.githubusercontent.com/8738114/35206945-099b28c4-ff7b-11e7-8235-383e3a91d479.png)

如果我选择只加载armeabi类型的话，会报错

**Comment by JenniferHuLL** [comment]
你把v8的拷贝下来 粘贴到下面试下  我的是可以的  不知道你的行不行哈

**Comment by bingoogolapple** [comment]
今晚下班回去改
