### ISSUE TITLE
 Zxing 图片识别错误

### ISSUE THREAD

**Issue by zhangchaojiong** [bingoogolapple/BGAQRCode-Android#228]
[二维码](https://i.imgur.com/G6gdMsF.png)

正确的 值是 ：`aHR0cHM6Ly9vYXV0aC5kbXN5cy5jb20vc2wvYXV0aD9jb2RlPWxaaV9HbnZWaGhzS1lIR09lOUp2 NXc=`
（使用QQ，微信都是扫描正确）
 使用  Zxing 错误了，扫出来是一个6位数的 数字。
在线求解。

**Comment by 799536960** [comment]
我也是 用zbar是正确的

**Comment by jarkeet** [comment]
请问如何解决 偶尔出现的这个神奇数字

**Comment by 799536960** [comment]
额 我换成zbar了 就好了 zxing的话要等修复吧

**Comment by zhangchaojiong** [comment]
@799536960  zbar 也是会出现这个神奇的数字。。

**Comment by 799536960** [comment]
哎 没有啊 你给的二维码 刚才我用作者的zbar demo扫了下 没问题啊 zxing demo扫有问题

**Comment by zhangchaojiong** [comment]
@799536960  你拿远一点点 扫一下。有几率 出现那个神奇的数字

**Comment by zhangchaojiong** [comment]
使用ZXING 3.3.2 本以为识别率会高点，没想到 比3.3.1 还不行。。希望作者能轻快适配 3.3.2，以及修复以上问题

**Comment by zhangchaojiong** [comment]
识别还有待优化。先这么用着吧！
