### ISSUE TITLE
zxing横屏识别不了条形码

### ISSUE THREAD

**Issue by CGmaybe10** [bingoogolapple/BGAQRCode-Android#23]
zxing横屏时，将条形码也横着放，就识别不了了，但是条形码竖着放又可以识别了。还没有仔细看代码，是不是把图片旋转一下这个问题就解决了。

**Comment by CGmaybe10** [comment]
是因为在ProcessDataTask.java的doInBackground()方法里旋转了数据，在旋转前判断一下横屏还是竖屏就可以了

**Comment by bingoogolapple** [comment]
用 v1.1.8 版本
