### ISSUE TITLE
 HINTS.put(DecodeHintType.TRY_HARDER, BarcodeFormat.QR_CODE);

### ISSUE THREAD

**Issue by qinweining** [bingoogolapple/BGAQRCode-Android#231]
HINTS.put(DecodeHintType.TRY_HARDER, BarcodeFormat.QR_CODE);   DecodeHintType.TRY_HARDER 表示花更多的时间用于寻找图上的编码，优化准确性，但不优化速度，Boolean类型；为什么value 是BarcodeFormat.QR_CODE

**Comment by bingoogolapple** [comment]
最新版已改正
