### ISSUE TITLE
Version 10以上的二维码无法识别

### ISSUE THREAD

**Issue by dfeng99** [bingoogolapple/BGAQRCode-Android#233]
Hi @bingoogolapple ，

我试着使用ZbarDemo 扫位于 [维基的QRCode范例](https://en.wikipedia.org/wiki/QR_code) ，发现Version 10以上的QRCode均无法扫描成功，请问有解药吗？还请惠于赐教！

大卫.

**Comment by dfeng99** [comment]
我发现，当扫高版本的QRCode时，图片要够大才能成功解码，所以如下的QRCode

![2018-02-07 3 55 54](https://user-images.githubusercontent.com/11707571/35904845-a7c38e50-0c1f-11e8-87c8-24bc765d3d50.png)

必須放大到一定比例才能被成功解碼，這是什麼原因呢？我使用Huawei MediaPad T2 (BGA-L03) 測試的。

在同樣的QRCode尺寸，一样使用zbarlib 作为开发基础，我在iPhone上可以识别，我没有深入地了解QRCode的解码原理，这跟镜头的像素有关吗？

**Comment by bingoogolapple** [comment]
应该和摄像头有关吧，具体不清楚。

[谷歌的 qr_codes 文档](https://developers.google.com/chart/infographics/docs/qr_codes) 里说最好的二维码阅读器能够读取版本 40，移动设备可能只能读取到版本 4，但我用 zxing 试了下能识别到 Version 25

![image](https://user-images.githubusercontent.com/8949716/41681075-1947765a-7506-11e8-874a-018bde714925.png)
