### ISSUE TITLE
在录入手机的IMEI码时，有几率出现返回结果不正确的问题

### ISSUE THREAD

**Issue by laohong** [bingoogolapple/BGAQRCode-Android#235]
出现的数字子是随机的，但是基本以010开头的居多，我看其他人也有提出这个问题的，但是不知为何一直没有解决

**Comment by laohong** [comment]
补充一下，用的是zbar1.2.1。下面是测试用的图片
![aa](https://user-images.githubusercontent.com/16670140/36656295-a9b3e966-1b02-11e8-8299-fdb893717ee0.png)

**Comment by bingoogolapple** [comment]
用最新版
