### ISSUE TITLE
当只识别扫描框区域的二维码，建议支持可以扩大实际扫描区域方法

### ISSUE THREAD

**Issue by cocolove2** [bingoogolapple/BGAQRCode-Android#237]
int expandScanSize=90; 
public Rect getScanBoxAreaRect(int previewHeight) {
        if (mIsOnlyDecodeScanBoxArea) {
            Rect rect = new Rect(mFramingRect);
            float ratio = 1.0f * previewHeight / getMeasuredHeight();
            rect.left = (int) (rect.left * ratio)-expandScanSize;
            rect.right = (int) (rect.right * ratio)+expandScanSize;
            rect.top = (int) (rect.top * ratio)-expandScanSize;
            rect.bottom = (int) (rect.bottom * ratio)+expandScanSize;
            return rect;
        } else {
            return null;
        }
    }

**Comment by tanranran** [comment]
这个算法千万别加，

你看我这张图你就知道了


![cd1d3bd4dc7d46563cdf9398bb0639d5](https://user-images.githubusercontent.com/5227840/37240157-b33fd358-2482-11e8-899e-005bb2e98651.png)

**Comment by tanranran** [comment]
你加了后，比如我扫码的是第一张二维码，但是实际的区域已经包含了下面的条形码，造成扫码效率会低很多

**Comment by bingoogolapple** [comment]
最新版已优化只识别扫描框区域的算法
