### ISSUE TITLE
识别率不高的另外一个原因，屏蔽掉会好一点

### ISSUE THREAD

**Issue by tanranran** [bingoogolapple/BGAQRCode-Android#240]
扫码识别区域有误

ScanBoxView 这个类中

getScanBoxAreaRect 方法中

float ratio = 1.0f * previewHeight / getMeasuredHeight();
rect.left = (int) (rect.left * ratio);
rect.right = (int) (rect.right * ratio);
rect.top = (int) (rect.top * ratio);
rect.bottom = (int) (rect.bottom * ratio);

这个算法有误

会造成，明明正中心对准的是二维码图片，但是经过这个算法放大的图片会出现向上和向右偏移

**Comment by bingoogolapple** [comment]
最新版已修复
