### ISSUE TITLE
zxing1.2.1引入出现如下错误

### ISSUE THREAD

**Issue by xinyangmaojian** [bingoogolapple/BGAQRCode-Android#242]
Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve cn.bingoogolapple:bga-zxing:1.2.1.
Open File "Unable to resolve dependency for &#39;:app@debug/compileClasspath&#39
 Could not resolve cn.bingoogolapple:bga-zxing:1.2.1."
Show Details

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve cn.bingoogolapple:bga-zxing:1.2.1.

Could not resolve cn.bingoogolapple:bga-zxing:1.2.1.
Required by:
    project :app
 > Could not resolve cn.bingoogolapple:bga-zxing:1.2.1.
    > Could not get resource 'https://dl.google.com/dl/android/maven2/cn/bingoogolapple/bga-zxing/1.2.1/bga-zxing-1.2.1.pom'.
          > Could not GET 'https://dl.google.com/dl/android/maven2/cn/bingoogolapple/bga-zxing/1.2.1/bga-zxing-1.2.1.pom'.
                   > Connect to dl.google.com:443 [dl.google.com/172.217.24.14] failed: Connection timed out: connect
                               > Connection timed out: connect

**Comment by fairytale110** [comment]
哎，链接超时，这点理解能力都没有么，，，
