### ISSUE TITLE
如何调整扫描框高度（条形码和二维码）

### ISSUE THREAD

**Issue by ypf168326** [bingoogolapple/BGAQRCode-Android#246]
扫描框宽带在自定义属性里面是有的，但是高度是哪个属性设置呢？

**Comment by bingoogolapple** [comment]
qrcv_rectWidth 不管是二维码还是一维码样式，宽度都是由这个指定
qrcv_barcodeRectHeight 一维码样式时，高度有这个指定
qrcv_isBarcode 设置是否为一维码样式
