### ISSUE TITLE
qrCodeTipText问题

### ISSUE THREAD

**Issue by sweet2o09** [bingoogolapple/BGAQRCode-Android#247]
查看1.2.0的Demo,qrCodeTipText只支持文字,希望能支持文字+图片
另外,ZXingView初始化后,代码修改qrCodeTipText无效,查看源码,发现ScanBoxView是在onDraw里面绘制了提示文本

**Comment by Vanish136** [comment]
同样的问题！

**Comment by bingoogolapple** [comment]
文字那个问题用最新版，图片接入方自己在外面包裹relativelayout来加吧
