### ISSUE TITLE
大概率出现不对准二维码扫描，会扫出一堆数字的问题

### ISSUE THREAD

**Issue by kaikaifly** [bingoogolapple/BGAQRCode-Android#248]

**Comment by yaochangliang159** [comment]
也遇到了这个情况

**Comment by androidmh** [comment]
这个是z-xing内部算法问题，会把有些二维码当作一维码来扫描，所以会出现这样的问题，只能自行判断

**Comment by evan505** [comment]
@kaikaifly 一般二维码不会放纯数字，搞个正则匹配下 重新扫描

**Comment by Carlos2927** [comment]
如果只是需要支持二维码，不需要同时支持一维码的话，可以在QRCodeDecoder的中将有关一维码的格式注释掉即可解决这个问题
![default](https://user-images.githubusercontent.com/12493233/40230324-afc41d4c-5ac9-11e8-9d16-c4c3e2f20d9f.png)

**Comment by androidmh** [comment]
@kaikaifly 我记得是返回的八位数字，所以你可以写个正则判断是否为8位数字，如果是就继续开启扫码不返回，当然了，如果你的二维码正好是八位数字的话，那可能要很倒霉了= =，顺带一提这个框架真的错误概率挺大的，推荐你换个框架，我后来换了一个框架，测试了1000+次暂时还没有出现返回数字的情况，这个的话1000次可能会返回170次左右的数字，可能更高，二维码越复杂出现概率越高

**Comment by kaikaifly** [comment]
@androidmh 请问你现在用的哪个框架，能否提供下github地址，谢谢啦

**Comment by kaikaifly** [comment]
@Carlos2927 谢谢你的建议，我到程序中试一下，

**Comment by androidmh** [comment]
@kaikaifly https://github.com/journeyapps/zxing-android-embedded

**Comment by qianshengta** [comment]
我就是扫描空白处也会有一串数字返回

**Comment by bingoogolapple** [comment]
用最新版

**Comment by hxkdidi** [comment]
@androidmh 换了https://github.com/journeyapps/zxing-android-embedded 还是有概率出现

**Comment by wscjy** [comment]
您好，我已收到您的邮件，我会尽快给您回复。
