### ISSUE TITLE
只用armeabi平台扫描不了

### ISSUE THREAD

**Issue by Reginer** [bingoogolapple/BGAQRCode-Android#253]
armeabi下的so应该是有问题的。扫描不出东西。

**Comment by lifei1245** [comment]
兄弟,这个库zbar不是只加gradle依赖么,哪里有so文件.

**Comment by Reginer** [comment]
这就尴尬了，依赖你不得下载下来么，指定一个armeabi试试看

**Comment by lifei1245** [comment]
这个zbar没有so的嘛,依赖是会下下来,指定armeabi是个什么意思..

**Comment by Reginer** [comment]
http://jcenter.bintray.com/cn/bingoogolapple/bga-qrcode-zbar/1.2.5/
下载里面aar，解压之后了解一下。
ndk了解一下

**Comment by lifei1245** [comment]
这个使用方式没说这样用的嘛,不是说在gradle里加
```gradle
implementation "cn.bingoogolapple:bga-qrcode-zbar:$rootProject.qrcodeVersion"
```就好了么,你这用aar的方式是哪里看到的

**Comment by Reginer** [comment]
你真是大哥，你知道这句话是怎么工作的么，就是从jCenter上把库下载下来，然后在本地进行编译的。

**Comment by lifei1245** [comment]
是啊, 这句话他也并没有下载so啊..

**Comment by Reginer** [comment]
so就在aar里啊，真不知道你怎么开发的，竟对这些一无所知 。。。

**Comment by lifei1245** [comment]
......我是说这个项目的使用说明里并没有让我使用aar,而是只让gradle配一句话

**Comment by Reginer** [comment]
没得救了，自己百度一下，为什么引用一句话就能用

**Comment by lifei1245** [comment]
我当然知道他是到jcenter仓库去拉的, 问你的是项目说明里哪里看到的要用aar的方式,你这飘的

**Comment by JarvanMo** [comment]
@lifei1245 zbar这个项目本身就是c写的。zbar已经不维护了，还有一些bug

**Comment by lifei1245** [comment]
@JarvanMo  请问下这个zbar和zxing有什么区别吗

**Comment by JarvanMo** [comment]
@lifei1245 而且就目前armeabi来说armeabi这种的cpu已经绝迹了，Realm已经不支持输出armeabi了。不推荐使用只用armeabi包，，会有很多兼容性问题。不要看微信，因为他 们都是动态加载的。
