### ISSUE TITLE
从有“测试扫描二维码”按钮的activity，进入扫描activity,进入的过程中会有上一个页面的残影

### ISSUE THREAD

**Issue by Seachal** [bingoogolapple/BGAQRCode-Android#257]
从有“测试扫描二维码”按钮的activity，进入扫描activity,进入的过程中会有上一个页面的残影

**Comment by my29** [comment]
我也是遇到这样的问题，每次跳转到扫码界面，都会显示一半的上个页面

**Comment by Seachal** [comment]
@my29 和手机的性能有一定的关系，对于配置低一些的（例如努比亚 z9）残影会比较明显，用配置高一些的（残影就不明显），目前是根据这两部手机得出的结论，并不一定准确。
