### ISSUE TITLE
Demo里忘调startSpot了吧

### ISSUE THREAD

**Issue by 4332weizi** [bingoogolapple/BGAQRCode-Android#258]
https://github.com/bingoogolapple/BGAQRCode-Android/blob/4c9dd00b587e65e2492a08d7842f6db132f5c99b/zxingdemo/src/main/java/cn/bingoogolapple/qrcode/zxingdemo/TestScanActivity.java#L36

看Demo被坑了，调了一下午为啥扫描不出来。。。。

**Comment by wukuiqing49** [comment]
他是在点击事件里边  开启扫描的     没有设置自动扫描

**Comment by 4332weizi** [comment]
是的，是我没看清楚，谢谢。:joy:
