### ISSUE TITLE
摄像机权限问题

### ISSUE THREAD

**Issue by wengwyue** [bingoogolapple/BGAQRCode-Android#26]
环境：魅族note1 系统android5.1
打开扫一扫页面时，系统会弹出请求拍照功能，如果用户选择了拒绝，则会黑屏，后面在此进入也是黑屏
这个问题请问你们有没有遇到这个，是怎么解决的，谢谢！

**Comment by wengwyue** [comment]
这种情况下，camera.open是catch不到错误的，需要在setcamera方法那里catch，所以打开相机错误的回调并没有调用。

**Comment by bingoogolapple** [comment]
@wengwyue 好哒，争取周末改了发个新版本

方便加qq群：196281253   等改好后发个版本给你测试一下吗？

**Comment by wengwyue** [comment]
可以啊


来自 魅蓝 note

-------- 原始邮件 --------
发件人：王浩 <notifications@github.com>
时间：周四 6月16日 13:01
收件人：bingoogolapple/BGAQRCode-Android <BGAQRCode-Android@noreply.github.com>
抄送：Andy Weng <wengwyue@163.com>,Mention <mention@noreply.github.com>
主题：Re: [bingoogolapple/BGAQRCode-Android] 摄像机权限问题 (#26)

**Comment by bingoogolapple** [comment]
@wengwyue 能加一下qq群吗，改好了，发你测试一下就发新版本

**Comment by inke88** [comment]
乐视2的x620手机，给所有相机权限，打开相机都是错误。
@Override
    public void onScanQRCodeOpenCameraError() {
        Log.e(TAG, "打开相机出错");
    }

**Comment by shaheyijiu** [comment]
自定义CaptureActivity,在里面判断用户是否给予应用相机权限，如果没有的话，finish掉该Activity，就不会出现黑屏了。@wengwyue
