### ISSUE TITLE
1.2.1版本ZBar扫描识别特别慢，1.1.8/1.19版本很快

### ISSUE THREAD

**Issue by moodd** [bingoogolapple/BGAQRCode-Android#267]
1.正在使用的是1.1.8版本，ZBar识别很快，今天升级1.2.1，测试了下，4-5秒才能识别，速度慢到无法接受；
2.1.2.0版本xml解析ZbarView错误，略过，是否因为中文乱码功能调整导致识别速度降低？
测试手机：华为荣耀V10
以上问题，希望能提供解决思路

**Comment by bingoogolapple** [comment]
用最新版优化了对焦方式
