### ISSUE TITLE
如何设置相机不自动变焦

### ISSUE THREAD

**Issue by Sujie1** [bingoogolapple/BGAQRCode-Android#276]

**Comment by Sujie1** [comment]
预览图被放大了

**Comment by Future-Bird** [comment]
我希望自动放大。。但却没有。
你怎么做到的

**Comment by Sujie1** [comment]
他有自动变焦的功能啊，集成好就有的

**Comment by Future-Bird** [comment]
我集成的zbar

**Comment by Future-Bird** [comment]
我集成的zbar确实没有自动变焦。。是因为调用不对吗

**Comment by Sujie1** [comment]
你看他startCamera()里面的源码
 public void showCameraPreview() {
        if (mCamera != null) {
            try {
                mPreviewing = true;
                mCamera.setPreviewDisplay(getHolder());

                mCameraConfigurationManager.setDesiredCameraParameters(mCamera);
                mCamera.startPreview();

                mCamera.autoFocus(autoFocusCB);
            } catch (Exception e) {
                Log.e(TAG, e.toString(), e);
            }
        }
    }

**Comment by Future-Bird** [comment]
用的1.2.1版本的zbar，源码里没有这段代码，我更新到1.2.5试试

**Comment by Sujie1** [comment]
implementation 'cn.bingoogolapple:bga-qrcode-zbar:1.2.1'
这个就有   你从startCamera()一级一级往下找

**Comment by Sujie1** [comment]
CameraPreview  这个类的最下边的方法

**Comment by Future-Bird** [comment]
确实是这样。。
但还是没有自动对焦，更新到1.2.5，或许是设备的问题。我再换个设备试试，谢谢你。

**Comment by Sujie1** [comment]
retrofit的token失效自动刷新问题，有做过吗？

**Comment by Future-Bird** [comment]
你看下这篇对你有没有帮助，https://www.jianshu.com/p/8d1ee61bc2d2

**Comment by Sujie1** [comment]
谢谢了   这些我都看过了
