### ISSUE TITLE
8.0的手机扫不了

### ISSUE THREAD

**Issue by yinxtno1** [bingoogolapple/BGAQRCode-Android#277]
8.0的手机无法扫描二维码

**Comment by xiaoxiaohua333** [comment]
我也是，使用pixel 8.0的扫描二维码无法识别，同时安装demo使用zxingview 也是无法识别。

**Comment by xiaoxiaohua333** [comment]
忘记调用         mZxingView.setDelegate(this);
扫码正常了。

**Comment by bingoogolapple** [comment]
我这边 Pixel2 8.0.0，小米 MIX2S 8.0.0 都可以。@yinxtno1 看下是不是 @xiaoxiaohua333 的原因
