### ISSUE TITLE
不去扫描任何东西，也会有一串数字回调

### ISSUE THREAD

**Issue by qianshengta** [bingoogolapple/BGAQRCode-Android#278]
我就打开扫描界面，摄像头朝下放在桌面上，一段时间后也会有一串数字返回。

**Comment by 562218352** [comment]
我也遇到了，请问你是怎么解决的？

**Comment by qianshengta** [comment]
我发现这种情况返回的总是一个16位数字， 我就在结果返回哪了加了个判断，是不是16位的数字，如果是的话就当做错误数据，提示用户重新去扫描。要是你扫描的数据也正好是16位的数字的话 那就没办法了

**Comment by bingoogolapple** [comment]
用最新版
