### ISSUE TITLE
ISBN 条形码识别不完整

### ISSUE THREAD

**Issue by iflove** [bingoogolapple/BGAQRCode-Android#289]
ISBN 条形码识别不完整

**Comment by iflove** [comment]
ISBN 13 ，zbar 扫描出来只有10位。原因是 ean.c 源文件做了ISBN-10优先于ISBN-13处理

`ISBN-10 has priority over ISBN-13(?)`

**Comment by bingoogolapple** [comment]
最新版在 Java 层不添加isbn10

**Comment by bingoogolapple** [comment]
最新版在 Java 层不添加isbn10
