### ISSUE TITLE
java.lang.RuntimeException: cancelAutoFocus failed，怎么解决

### ISSUE THREAD

**Issue by dyalexamor** [bingoogolapple/BGAQRCode-Android#296]
扫描出现java.lang.RuntimeException: cancelAutoFocus failed，mQRCodeView.stopCamera()报错，怎么解决？
   @Override
    protected void onStop() {
        mQRCodeView.stopCamera();
        super.onStop();
    }

**Comment by bingoogolapple** [comment]
用最新版
