### ISSUE TITLE
小米手机用户确认权限后不会显示画面需要重新打开APP才显示

### ISSUE THREAD

**Issue by bluwil** [bingoogolapple/BGAQRCode-Android#298]
小米手机targetSdkVersion较高，在将statusBar设置为透明的情况下。同意相机权限过后调用startSpotAndShowRect画面不显示，需要重新打开APP才显示画面，不设置statusBar为透明则正常显示。
在调用startSpotAndShowRect之后利用反射调用CameraPreview类的showCameraPreview函数画面正常显示。原因是在同意权限过后调用startSpotAndShowRect不会触发surfaceChanged回调
```
            if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                startScan()//同意权限过后调用startSpotAndShowRect
            }
```

```
//源码
    void setCamera(Camera camera) {
        mCamera = camera;
        if (mCamera != null) {
            mCameraConfigurationManager = new CameraConfigurationManager(getContext());
            mCameraConfigurationManager.initFromCameraParameters(mCamera);

            getHolder().addCallback(this);
            if (mPreviewing) {
                requestLayout();//以上情况不会触发surfaceChanged回调
            } else {
                showCameraPreview();
            }
        }
    }
```

**Comment by Harris-wu** [comment]
非常感谢 我也遇到这个问题了 在你的提示下 通过反射修复了BUG 下面是反射代码：
try {
            Field mPreviewField = mZXingView.getClass().getSuperclass().getDeclaredField("mPreview");
            mPreviewField.setAccessible(true);
            CameraPreview mPreview = (CameraPreview) mPreviewField.get(mZXingView);
            Field mPreviewingField = mPreview.getClass().getDeclaredField("mPreviewing");
            mPreviewingField.setAccessible(true);
            mPreviewingField.set(mPreview,false);
        } catch (Exception e) {
            e.printStackTrace();
        }
        mZXingView.startCamera();
        mZXingView.startSpotAndShowRect();

**Comment by int123** [comment]
Field mPreviewField = mZXingView.getClass().getSuperclass().getDeclaredField("mPreview");
 其中mPreview是哪里定义的？为啥我这报错，找不到它？

**Comment by int123** [comment]
解决了我的问题，谢谢

**Comment by Hiboboo** [comment]
@Harris-wu 
哥们，我照着你的代码敲进去后，虽然在状态栏透明的情况下可以直接进行扫描（之前是需要重新打开一次的），但是，新的问题是一直没有扫描结果，还是重新打开之后才可以，你那边遇到这问题了吗？

**Comment by CaoJieNan** [comment]
小米手机申请摄像头权限确实有这个问题，已解决
