### ISSUE TITLE
经常依赖找不到这个

### ISSUE THREAD

**Issue by xionger0520** [bingoogolapple/BGAQRCode-Android#305]
org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not HEAD 'https://jitpack.io/cn/bingoogolapple/bga-qrcode-zxing/1.2.5/bga-qrcode-zxing-1.2.5.pom'. Received status code 401 from server: Unauthorized

**Comment by conghuahuadan** [comment]
我也是

**Comment by xionger0520** [comment]
跪求作者看看这个问题  万一正忙着出现这个问题 就完了

**Comment by xionger0520** [comment]
@bingoogolapple

**Comment by conghuahuadan** [comment]
我目前解决方法是从jcenter下载使用本地依赖

**Comment by bingoogolapple** [comment]
我只传了 jcenter，看README里写的依赖
