### ISSUE TITLE
該如何將掃瞄線去除

### ISSUE THREAD

**Issue by ShuchengFu** [bingoogolapple/BGAQRCode-Android#312]
嗨各位大大，
我在scan xml 佈局中把掃瞄線拿掉後 app:qrcv_customScanLineDrawable="@drawable/scan_icon_scanline"
發現他還是有定義一條白線，該如何將掃瞄線直接拿掉的方法呢? 有人有做過嗎? 謝謝

**Comment by bing27** [comment]
色值改成透明
