### ISSUE TITLE
扫描二维码的时候 二维码不用完全放到扫描框中也可以扫描成功

### ISSUE THREAD

**Issue by longchenpl** [bingoogolapple/BGAQRCode-Android#33]
扫描二维码的时候 二维码不用完全放到扫描框中也可以扫描成功，貌似扫描框作用不大啊~

**Comment by bingoogolapple** [comment]
@longchenpl 谢谢反馈。用户也是希望尽快扫出来执行下一步操作，新浪微博的二维码也是这么干的。你提的这个后面空了可能会考虑优化，但是最近不会这么做

**Comment by longchenpl** [comment]
好的 谢谢大神

**Comment by nangonghuang** [comment]
虽然关闭了，还是想说一下。这个库的代码里面扫描框的范围是没起作用的，直接解码的整个相机图片.....在电视机这种大屏幕上显示出来的二维码超级超级超级难识别，困扰了我很久，=。=最后我把代码下下来，把这个扫描范围改成扫描框范围才好。。还有就是建议扫描结果里面把扫描的图片范围给传出来，方便调试用。。。

**Comment by longchenpl** [comment]
@nangonghuang   求大神代码

**Comment by bingoogolapple** [comment]
@nangonghuang 「把这个扫描范围改成扫描框范围才好」能不能改了来提个PR

**Comment by nangonghuang** [comment]
@longchenpl  
不会玩这个。。。
在ScanBoxView里面增加一个方法public Rect getFramingRect(){
        return mFramingRect ;
    }
在ZXingView里面 processData里面改一下new  PlanarYUVLuminanceSource的参数，
 Rect rect = mScanBoxView.getFramingRect();
source = new PlanarYUVLuminanceSource(data, width, height, rect.left, rect.top, rect.width(), rect.height(), false);
你试试看

**Comment by nangonghuang** [comment]
@bingoogolapple 
git我基本忘光了，不会玩了，上面我提了，你自己看着改吧。。

**Comment by bingoogolapple** [comment]
后面空了我试着改一下

[推荐看下这个](http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000)

**Comment by longchenpl** [comment]
@nangonghuang 感谢大神

**Comment by bingoogolapple** [comment]
@nangonghuang 你这种方式还是有问题，top和bottom不准备，我改了下。你后面更新到v1.1.1吧
