### ISSUE TITLE
请问能不能加快对焦速度

### ISSUE THREAD

**Issue by snsdTJ** [bingoogolapple/BGAQRCode-Android#346]
请问能不能加快进入扫描界面的对焦速度，我手机进入扫描界面时对焦差不多要3秒左右，然后才开始识别，之后扫描识别都很快，就是刚进扫描界面时很慢。
希望有时间时能不能改进一下。
非常感谢开源这个扫码库。

**Comment by bingoogolapple** [comment]
用最新版 v1.3.5 试试
