### ISSUE TITLE
请教！二维码识别速度慢，屏幕上二维码很清晰但是还是识别不出来

### ISSUE THREAD

**Issue by JoinBelieve** [bingoogolapple/BGAQRCode-Android#348]
有时远近调一下可以，是我哪里设置有问题？能不能像微信那样识别的很快

**Comment by JoinBelieve** [comment]
![image](https://user-images.githubusercontent.com/29223055/47705475-a2703080-dc61-11e8-829f-fe82e0ae4d0a.png)

**Comment by JoinBelieve** [comment]
![image](https://user-images.githubusercontent.com/29223055/47705506-b74cc400-dc61-11e8-91a6-17a8430e4293.png)

**Comment by JoinBelieve** [comment]
dome中识别速度很快

**Comment by JoinBelieve** [comment]
调好了，是设置的问题

**Comment by zhangranran** [comment]
请问你是怎么处理的？我也遇到了相同的问题

**Comment by JoinBelieve** [comment]
@zhangranran 
app:qrcv_isOnlyDecodeScanBoxArea="false"
qrcv_rectWidth 改大了些

**Comment by JoinBelieve** [comment]
但是还是没有微信给力，第一次聚焦需要手动点一下，识别才快。

**Comment by zhangranran** [comment]
@JoinBelieve 谢谢

**Comment by bingoogolapple** [comment]
试试最新版 v1.3.5
