### ISSUE TITLE
QRCodeView能否增加setType的公共方法，让子类去实现，这样调用会方便一些

### ISSUE THREAD

**Issue by HsXuTao** [bingoogolapple/BGAQRCode-Android#362]
QRCodeView能否增加setType的公共方法，让子类去实现，这样调用会方便一些

**Comment by bingoogolapple** [comment]
ZXingView 和 ZBarView 已经有对应的 setType 方法了，第一个参数一样，第二个参数 zxing 和 zbar 不一样，库里没有对其在统一了
