### ISSUE TITLE
1.3.4.aar 无法下载

### ISSUE THREAD

**Issue by chinamingsss** [bingoogolapple/BGAQRCode-Android#365]
android studio 3.2.1 版本依赖1.3.4版本报错 Can not get resouse 。。。1.3.4.aar

**Comment by githubchen001** [comment]
在 build.gradle 把 jcenter() 换成 jcenter { url "http://jcenter.bintray.com/"} 就好了，被和谐了你懂得

**Comment by githubchen001** [comment]
·

> android studio 3.2.1 版本依赖1.3.4版本报错 Can not get resouse 。。。1.3.4.aar

在 build.gradle 把 jcenter() 换成 jcenter { url "http://jcenter.bintray.com/"} 就好了，被和谐了你懂得
