### ISSUE TITLE
【bug】相册选取条形码进行识别，程序崩溃

### ISSUE THREAD

**Issue by txadf** [bingoogolapple/BGAQRCode-Android#37]

**Comment by bingoogolapple** [comment]
@txadf 麻烦提供一下错误日志

**Comment by bingoogolapple** [comment]
demo里演示的是解析bitmap里的二维码，你这个问题是解析的过程错误，还是选取图片的过程错误

**Comment by txadf** [comment]
我是直接安装你提供的APK文件，出现的错误，然后就没有看代码了。我在弄识别二维码或者条形码时用MultiFormatReader 这个类，可以识别图片中 的条形码，但是效率不是很高

**Comment by bingoogolapple** [comment]
是我提供的二维码载的apk在你手机上崩溃？

**Comment by txadf** [comment]
是的，这个ZXingDemo.apk（测试扫描二维码-->从相册选取扫描），我是选取的含有二维码的图片测试的，含有条形码的也是的。

**Comment by bingoogolapple** [comment]
手机是什么机型，方便clone源码跑demo看看具体的报错信息吗

**Comment by txadf** [comment]
华为荣耀3X，android4.4.2。现在有点事，晚点弄源码，最迟明晚前给你回复。

**Comment by txadf** [comment]
抱歉，不能给出报错信息了，源码弄到as没有成功，就放弃了。

**Comment by bingoogolapple** [comment]
我把从相册选择二维码图片的逻辑了，你重新载 [ZXingDemo.apk](http://fir.im/ZXingDemo) 试试

**Comment by txadf** [comment]
可以了，没有问题了。如果从图片中选择，图片中的条形码或者二维码比较小，识别率很低，你有没有什么解决办法。

**Comment by bingoogolapple** [comment]
应该是之前从图库选择图片的方法在你手机上不兼容吧。

「图片中的条形码或者二维码比较小，识别率很低」重新传了apk的，你再重新下载上面连接里的apk试试，最新版的apk还有这个问题？

**Comment by txadf** [comment]
没有，就是你说的，条码比较小识别率比较低。
