### ISSUE TITLE
关于华为手机二维码识别的问题

### ISSUE THREAD

**Issue by wukuiqing49** [bingoogolapple/BGAQRCode-Android#373]
测试结果
华为mate 10 扫码成功未发现问题
华为荣耀8 手机平度亮度低的情况下未扫描到二维码,  调高屏幕亮度后 水平位置且适当距离40公分左右扫码成功,倾斜角度依然识别不出来二维码.

猜想:
       1:二维码识别的时候自动对焦功能是否在荣耀手机上起作用
       2;二维码识别是否和屏幕亮度有关
       3:手机本身的防抖功能是否会影响二维码识别的效果.

**Comment by bingoogolapple** [comment]
@wukuiqing49 能否加 QQ 帮看测一下是否有问题

496312716

**Comment by wukuiqing49** [comment]
哥们你qq多少  我的 1571478933

**Comment by wukuiqing49** [comment]
华为手机的问题 部分机型测试 没问题了  楼主威武

**Comment by bingoogolapple** [comment]
最新版可以了？

**Comment by wukuiqing49** [comment]
可以了  楼主威武
