### ISSUE TITLE
二维码识别不出来，用微信，支付宝可以正常识别。

### ISSUE THREAD

**Issue by wZuriel** [bingoogolapple/BGAQRCode-Android#385]
![91508ad3d8464047a98c07d376037570 1](https://user-images.githubusercontent.com/15941713/50584194-0359f600-0ea9-11e9-97e0-9ddf61b20fb6.png)
机型：红米4A 版本：Android 6.0.1
用zxing和zbar的demo都不能识别

**Comment by DophiGo** [comment]
这个问题解决了吗？分享一下解决方案

**Comment by JunWeiAndroid** [comment]
这个是可以扫出来的
