### ISSUE TITLE
在申请权限后，可以预览，但是无法识别

### ISSUE THREAD

**Issue by StaticCoder** [bingoogolapple/BGAQRCode-Android#386]
ver:1.3.6
手机型号:ALL models
在扫码界面第一次申请权限后，可以预览，但是无法识别，没有错误日志。后面重新进就可以了。
代码如下，在onStart中申请权限，在onPermissionsGranted回调中开启预览和识别：

@Override
    protected void onStart() {
        super.onStart();
        requestCodeQRCodePermissions();
    }

@AfterPermissionGranted(REQUEST_CODE_QRCODE_PERMISSIONS)
    private void requestCodeQRCodePermissions() {
        String[] perms = {Manifest.permission.CAMERA, Manifest.permission.READ_EXTERNAL_STORAGE};
        if (!EasyPermissions.hasPermissions(this, perms)) {
            EasyPermissions.requestPermissions(this, "扫描二维码需要打开相机权限", REQUEST_CODE_QRCODE_PERMISSIONS, perms);
        } else {
            zxingview.startCamera(); // 打开后置摄像头开始预览，但是并未开始识别
            zxingview.startSpotAndShowRect(); // 显示扫描框，并开始识别
        }
    }

@Override
    public void onPermissionsGranted(int requestCode, List<String> perms) {
        zxingview.startCamera(); // 打开后置摄像头开始预览，但是并未开始识别
        zxingview.startSpotAndShowRect(); // 显示扫描框，并开始识别
    }

**Comment by liuxinyea** [comment]
********

**Comment by StaticCoder** [comment]
这几天修复了几个bug：
部分机型上的Crop rectangle does not fit within image data.

**Comment by vzhilong** [comment]
怎么修复的？我出现了一样的问题，第一次授权后无法识别。

**Comment by vzhilong** [comment]
> ### 已解决，这几天修复了这个库的几个bug：
> 1. 部分机型上的异常Crop rectangle does not fit within image data.
> 2. 定位点偏移的问题.
> 3. 在扫码界面第一次申请相机权限后可以预览，但是无法识别.
> 
> 如果有人需要的话可以评论。
> 
> PS：
> 
> 1. up主的这个库封装的确实好用。
> 2. 加了两次讨论QQ群但是群主都没通过，不知道什么原因。

求助，发现sufface创建有问题。

**Comment by wZuriel** [comment]
第一次授权后无法识别怎么解决的

**Comment by StaticCoder** [comment]
> 怎么修复的？我出现了一样的问题，第一次授权后无法识别。



> 第一次授权后无法识别怎么解决的

只需要把CameraPreview.java中的第315行：
return mCamera != null && mPreviewing && mSurfaceCreated;
改成：
return mCamera != null && mPreviewing; 即可。
判断surface是否创建的意义不大。

**Comment by helixs** [comment]
@StaticCoder 666 不得不把代码拉下来

**Comment by wyj365372704** [comment]
> @StaticCoder 666 不得不把代码拉下来

可以通过反射修改这个变量。

if (permission.granted) {
                            {
                                final Field mCameraPreviewField = mZXingView.getClass().getSuperclass().getDeclaredField("mCameraPreview");
                                mCameraPreviewField.setAccessible(true);
                                final CameraPreview cameraPreview = (CameraPreview) mCameraPreviewField.get(mZXingView);
                                final Field mSurfaceCreatedField = cameraPreview.getClass().getDeclaredField("mSurfaceCreated");
                                mSurfaceCreatedField.setAccessible(true);
                                mSurfaceCreatedField.set(cameraPreview, true);//解决第一次授权进入后，无法识别二维码的问题。
                            }
                            mZXingView.startSpotAndShowRect(); // 显示扫描框，并开始识别
                        }

**Comment by StaticCoder** [comment]
> > @StaticCoder 666 不得不把代码拉下来
> 
> 可以通过反射修改这个变量。
> 
> if (permission.granted) {
> {
> final Field mCameraPreviewField = mZXingView.getClass().getSuperclass().getDeclaredField("mCameraPreview");
> mCameraPreviewField.setAccessible(true);
> final CameraPreview cameraPreview = (CameraPreview) mCameraPreviewField.get(mZXingView);
> final Field mSurfaceCreatedField = cameraPreview.getClass().getDeclaredField("mSurfaceCreated");
> mSurfaceCreatedField.setAccessible(true);
> mSurfaceCreatedField.set(cameraPreview, true);//解决第一次授权进入后，无法识别二维码的问题。
> }
> mZXingView.startSpotAndShowRect(); // 显示扫描框，并开始识别
> }

我对反射不太熟，如果你测试过可以的话，也是不错的解决方案。

**Comment by bingoogolapple** [comment]
> ### 已解决，这几天修复了这个库的几个bug：
> 1. 部分机型上的异常Crop rectangle does not fit within image data.
> 2. 定位点偏移的问题.
> 3. 在扫码界面第一次申请相机权限后可以预览，但是无法识别.
> 
> 如果有人需要的话可以评论。
> 
> PS：
> 
> 1. up主的这个库封装的确实好用。
> 2. 加了两次讨论QQ群但是群主都没通过，不知道什么原因。

@StaticCoder 求 PR

基本没登 QQ 了

**Comment by alidili** [comment]
> > @StaticCoder 666 不得不把代码拉下来
> 
> 可以通过反射修改这个变量。
> 
> if (permission.granted) {
> {
> final Field mCameraPreviewField = mZXingView.getClass().getSuperclass().getDeclaredField("mCameraPreview");
> mCameraPreviewField.setAccessible(true);
> final CameraPreview cameraPreview = (CameraPreview) mCameraPreviewField.get(mZXingView);
> final Field mSurfaceCreatedField = cameraPreview.getClass().getDeclaredField("mSurfaceCreated");
> mSurfaceCreatedField.setAccessible(true);
> mSurfaceCreatedField.set(cameraPreview, true);//解决第一次授权进入后，无法识别二维码的问题。
> }
> mZXingView.startSpotAndShowRect(); // 显示扫描框，并开始识别
> }

@wyj365372704 这个方法不错，试了下可以，不用拷源码了

**Comment by bingoogolapple** [comment]
@alidili 1.3.7 中已修复
