### ISSUE TITLE
为什么第一次打开无法正确扫描？？？

### ISSUE THREAD

**Issue by Hiboboo** [bingoogolapple/BGAQRCode-Android#422]
在我第一次打开二维码扫描页面后，相机和文件管理器的权限已获取到之后，我开始调用
``mQrcodeView.startCamera(); 
mQrcodeView.startSpotAndShowRect();
``
这两个方法，然后屏幕就似黑非黑的在那，具体看下图效果：
![微信截图_20190423145302](https://user-images.githubusercontent.com/11403290/56560623-85486900-65d7-11e9-8323-272b041f3022.png)

然后我查看后台日志，发现几行红色的，看下图：
![TIM截图20190423144536](https://user-images.githubusercontent.com/11403290/56560642-985b3900-65d7-11e9-9a74-5d69abba2a4f.png)

之后把扫码页面关掉再进来，就一切正常了。
我不知道这个究竟是怎么回事，求解答。

**Comment by davidgerka** [comment]
我也遇到这个问题，在扫描Activity的onResume方法里申请权限，获取权限后，开启相机和扫描，无法扫描。然后进入后台，再回到前台，就能正常扫描，不知道咋回事

**Comment by keenki** [comment]
遇到同样的问题。第一次获取权限后有些手机黑屏，有些手机能扫描但是无法对焦和开启手电筒。退出再重新进就好了。

**Comment by keenki** [comment]
看了之前的issue解决办法只能是在进入扫码页前获取权限？
https://github.com/bingoogolapple/BGAQRCode-Android/issues/152

**Comment by Hiboboo** [comment]
@keenki 我也看了其他的解决办法，最接近这个问题的是[https://github.com/bingoogolapple/BGAQRCode-Android/issues/298](url)，但治标不治本，在某些机型上是没问题了，但在其他高版本API的设备上还是无法扫描。

**Comment by Lindroy** [comment]
#152 感觉都没有解决问题，为什么close了？

**Comment by davidgerka** [comment]
想到一种处理方法：在ScanCodeActivity里面装ScanCodeFragment，在Activity启动时申请权限，获取权限之后，再去add Fragment，就可以解决第一次无法扫描的问题了。
当然最好还是能够把这个bug解决啦 哈哈

**Comment by Lindroy** [comment]
> 
> 
> 想到一种处理方法：在ScanCodeActivity里面装ScanCodeFragment，在Activity启动时申请权限，获取权限之后，再去add Fragment，就可以解决第一次无法扫描的问题了。
> 当然最好还是能够把这个bug解决啦 哈哈

我就是这么做的，不过我本来用的就是Fragment。

**Comment by Hiboboo** [comment]
@davidgerka @Lindroy 你俩真优秀

**Comment by a798284971** [comment]
我能说我放了个大招，用Activity.recreate() 去解决这个问题么。。

**Comment by windworst** [comment]
> 我能说我放了个大招，用Activity.recreate() 去解决这个问题么。。

哈哈哈厉害了

**Comment by HyanCat** [comment]
先将 View visibility 设为 GONE，获取权限后（startCamera 之前）设为 VISIBLE。

**Comment by FlyAwayL** [comment]
> Same issue.
> 
> 我是先将 View visibility 设为 GONE，获取权限后（startCamera 之前）设为 VISIBLE。

用这个，第一次扫码正常了。

**Comment by riwello** [comment]
用ViewStub懒加载可破
