### ISSUE TITLE
为什么我下载了ZXing的Demo扫描二维码没有效果呢？

### ISSUE THREAD

**Issue by davidllll** [bingoogolapple/BGAQRCode-Android#45]

**Comment by bingoogolapple** [comment]
默认没有开启识别二维码，需要点一下界面上的「开始识别」按钮

**Comment by 413970435** [comment]
你好，我使用的测试手机三星S7 Android6.0系统，使用ZXing的Demo识别多种二维码并点击屏幕上的开始识别等按钮都无效果，不过选择手机相册里的图片进行扫描是有效果的。系统相机权限确认打开，使用ZBar Demo扫描可以正常识别扫描二维码

**Comment by GitACDreamer** [comment]
我用你这个ZXingDemo扫描一个很清晰的二维码半天才能识别，有没有一个这样的功能：“扫一维码二维码自己自动切换识别?”

**Comment by bingoogolapple** [comment]
在布局文件里把 qrcv_isOnlyDecodeScanBoxArea 设置成 false 试试
