### ISSUE TITLE
扫码功能在Nexus 5.x（Android 6.0.1）上面失效

### ISSUE THREAD

**Issue by feijilbj** [bingoogolapple/BGAQRCode-Android#46]
新版的[barcodescanner](https://github.com/dm77/barcodescanner)已经解决，问题应该是自动聚焦捕获图像帧异常和解析的相关问题

**Comment by bingoogolapple** [comment]
麻烦试试 v1.1.4 能不能识别

**Comment by feijilbj** [comment]
还是无法识别条形码

**Comment by bingoogolapple** [comment]
二维码呢

**Comment by feijilbj** [comment]
也不可以

**Comment by wanghengx** [comment]
mQRCodeView.getScanBoxView().setOnlyDecodeScanBoxArea(true); 你是否使用了这个属性,去掉可以扫描出
