### ISSUE TITLE
zxing扫码在三星 Galaxy Note4上失效

### ISSUE THREAD

**Issue by wanglu123run** [bingoogolapple/BGAQRCode-Android#50]
目前在Galaxy Note4上全屏识别时能扫描，只识别扫描框区域时报错「java.lang.IllegalArgumentException: Crop rectangle does not fit within image data.」
可能因为processData方法里没有对图片的旋转进行判断。

**Comment by bingoogolapple** [comment]
在布局文件里把 qrcv_isOnlyDecodeScanBoxArea 设置成 false 试试

**Comment by StaticCoder** [comment]
#395
