### ISSUE TITLE
自定义logo可以从网络获取吗？

### ISSUE THREAD

**Issue by bobingxin** [bingoogolapple/BGAQRCode-Android#51]

**Comment by bingoogolapple** [comment]
这个需要你自己获取网络图片并将其转换成 Bitmap，然后传给 QRCodeEncoder 的 syncEncodeQRCode 方法，源码里每个方法都有注释的哦

![image](https://cloud.githubusercontent.com/assets/8949716/19920341/20e7df6c-a113-11e6-8d47-7fb4d67330a5.png)
