### ISSUE TITLE
有没有办法分别设置扫描框的宽度和高度

### ISSUE THREAD

**Issue by xiaoguxg** [bingoogolapple/BGAQRCode-Android#52]
现在高度和宽度好像是一样的，最好能够分别设置宽度和高度

**Comment by bingoogolapple** [comment]
二维码样式扫描时扫描线是从上到下，扫描框宽高必须相等，通过 rectWidth 设置；条形码扫描样式时扫描线是从左到右移动，能单独设置宽高

**Comment by gushoubang** [comment]
嗯，但是微信的好像宽比较大一点
