### ISSUE TITLE
照着demo敲，无法扫描二维码，下载demo apk 仍然无法使用扫一扫功能，扫相册倒是可以

### ISSUE THREAD

**Issue by HeweiZhang** [bingoogolapple/BGAQRCode-Android#53]

**Comment by bingoogolapple** [comment]
什么机型？demo apk里你有点击 开始识别 按钮吗

**Comment by HeweiZhang** [comment]
点击了  ，多种方式都试过，开始识别/开始识别显示扫描框，二维码跟条形码都不行，测试机型：魅族mx3，小米3          从图库选择二维码扫描没问题

**Comment by bingoogolapple** [comment]
在你那边没有一台手机能识别？

**Comment by HeweiZhang** [comment]
目前就测试了这两台

**Comment by bingoogolapple** [comment]
这两台手机拍照片后是不是需要在代码里旋转角度

**Comment by HeweiZhang** [comment]
我平时做拍照上传的时候可以直接用的 不需要特殊处理，用简单的zxing集成 ，可以扫描成功，只不过短时间内要改ui比较困难，所以想用你们的，感谢你们的付出

**Comment by bingoogolapple** [comment]
现在用 zxing 能识别了？

**Comment by bingoogolapple** [comment]
在布局文件里把 qrcv_isOnlyDecodeScanBoxArea 设置成 false 试试
