### ISSUE TITLE
android6.0 扫码闪退

### ISSUE THREAD

**Issue by yangyingdong** [bingoogolapple/BGAQRCode-Android#563]
android 6.0的手机扫码闪退  回调不了onScanQRCodeSuccess  有小伙伴遇到吗

**Comment by wscjy** [comment]
您好，我已收到您的邮件，我会尽快给您回复。

**Comment by yangyingdong** [comment]
之前用的implementation 'com.google.zxing:core:3.4.1'

**Comment by yangyingdong** [comment]
改为implementation 'com.google.zxing:core:3.3.3'就可以了
