### ISSUE TITLE
How to change position show Rect

### ISSUE THREAD

**Issue by Noobknight** [bingoogolapple/BGAQRCode-Android#57]
Hi !
Can me change position of Rect scan to center vertical and horizontal of camera screen ?
Thanks !

**Comment by bingoogolapple** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    style="@style/MatchMatch">

    <cn.bingoogolapple.qrcode.zxing.ZXingView
        android:id="@+id/zxingview"
        style="@style/MatchMatch"
        app:qrcv_isCenterVertical="true"
        app:qrcv_toolbarHeight="?attr/actionBarSize" />

    <android.support.v7.widget.Toolbar 
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    android:layout_alignParentTop="true"
    android:background="@color/colorPrimary"
    android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar" />
</RelativeLayout>
```

Using RelativeLayout as root
app:qrcv_toolbarHeight    equals   Toolbar's height
app:qrcv_isCenterVertical="true"

**Comment by Noobknight** [comment]
Not working !

My xml : 
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:weightSum="1">

    <ImageView
        android:id="@+id/activity_qrcode_imgIcon"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_marginTop="20dp"
        android:layout_weight="0.15"
        android:src="@drawable/ic_nomaps" />

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginLeft="20dp"
        android:layout_marginRight="20dp"
        android:layout_weight="0.85">

        <cn.bingoogolapple.qrcode.zbar.ZBarView
            android:id="@+id/zbarview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:qrcv_isCenterVertical="true"
            />
    </RelativeLayout>

    <Button
        android:id="@+id/activity_qrcode_btnBack"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="3dp"
        android:layout_marginLeft="17dp"
        android:layout_marginTop="10dp"
        android:text="@string/back_action" />

</LinearLayout>`

**Comment by bingoogolapple** [comment]
Using RelativeLayout as 「layout root」, 「specify Toolbar's height」

app:qrcv_toolbarHeight equals Toolbar's height
app:qrcv_isCenterVertical="true"
