### ISSUE TITLE
zbarview 扫描结果中文乱码如何解决

### ISSUE THREAD

**Issue by yuiopt** [bingoogolapple/BGAQRCode-Android#60]

**Comment by bingoogolapple** [comment]
先用zxing吧

**Comment by Dawnton** [comment]
替换一下so库就可以了,地址:http://pan.baidu.com/s/1o8cYVwu------密码:uft9

**Comment by yuiopt** [comment]
@Dawnton 这样的话不能用gradle添加依赖了吧？

**Comment by Dawnton** [comment]
就是替换个so文件 其他的不用动

**Comment by 79660095** [comment]
@Dawnton  替换了so文件也不行啊，扫 呵呵还是乱码

**Comment by qinyang1018** [comment]
zbar乱码是因为so库中的编码格式需要改成utf-8  可以自己编译个

**Comment by Dawnton** [comment]
@79660095 那可能是我发的那个so库和你的手机CPU类型匹配不上吧,你可以自己全都编译一下

**Comment by Xanthuim** [comment]
@qinyang1018 so库的源码在哪儿？

**Comment by Xanthuim** [comment]
@Dawnton 源文件在哪儿呢？

**Comment by Xanthuim** [comment]
自己编译的话在ZBar项目下这个文件里面改，ZBar/zbar/qrcode/qrdectxt.c，附带别人的解决办法
http://blog.csdn.net/duanhai189/article/details/8770042

**Comment by bingoogolapple** [comment]
implementation 'cn.bingoogolapple:bga-qrcode-zbar:1.2.0'
