### ISSUE TITLE
zxing在解析二维码的时候报错

### ISSUE THREAD

**Issue by xkun1** [bingoogolapple/BGAQRCode-Android#62]
com.google.zxing.NotFoundException

请问这个错误怎么解决，

**Comment by bingoogolapple** [comment]
gradle里添加依赖啊

```
compile 'com.google.zxing:core:3.2.1'
```

**Comment by xkun1** [comment]
添加啦，这个肯定有，但就是有点二维码解析就会抛出这个异常

**Comment by xkun1** [comment]
![image](https://cloud.githubusercontent.com/assets/15275629/18240598/52b028c2-737f-11e6-9d8c-f8276fcd71b6.png)
这个二维码解析失败，但是扫描ok，麻烦解答下

**Comment by nangonghuang** [comment]
我用我整合进去的功能，扫描和解析你上面的二维码是没问题的。。http://58.61.28.218:8081/rptSharePlat/er/r/ODliaWdkYXRhLmFkbWlu

**Comment by bingoogolapple** [comment]
你上面那个二维码我这边是能扫描出来的，在布局文件里把 qrcv_isOnlyDecodeScanBoxArea 设置成 false 试试
