### ISSUE TITLE
Zxing跟zbar都扫描无效

### ISSUE THREAD

**Issue by CrazyTaro** [bingoogolapple/BGAQRCode-Android#64]
不知道是程序识别的问题还是使用的问题.但是根据作者提供的代码进行创建的,但是没有任何数据返回.
PS,下载的zxingDemo相同,也无法识别扫描,包括对作者提借的下载的二维码也是一样不能识别.微信可以,通过微信扫描下载的.

**Comment by bingoogolapple** [comment]
* 看 README 里的「常见问题1」
* 跑demo的时候是否有点击「开始识别」按钮
* 返回问题的时候麻烦提供机型和系统版本号

**Comment by bingoogolapple** [comment]
把 qrcv_isOnlyDecodeScanBoxArea 设置成 false 试试
