### ISSUE TITLE
实测三星s6用zxing的demo扫不出来

### ISSUE THREAD

**Issue by Wade-Cai** [bingoogolapple/BGAQRCode-Android#68]
zxing的在nexus6，小米，华为，魅族，努比亚都没有问题的，三星一款低端的（忘了型号）也可以，但是三星s6就不行，之前用的另一个作者的zxing修改库https://github.com/yipianfengye/android-zxingLibrary
这个库用三星s6扫描是没有问题的，另外作者您的zbar可以扫描成功，所以应该是作者您修改的zxing有些问题。

**Comment by jingtianxiaozhi** [comment]
???

**Comment by jingtianxiaozhi** [comment]
没回答吗？

**Comment by jingtianxiaozhi** [comment]
三星s6不能用。

**Comment by Wade-Cai** [comment]
@jingtianxiaozhi  您换了哪个库呢，求推荐

**Comment by jingtianxiaozhi** [comment]
zxing

**Comment by eversky** [comment]
vivo y51 用zxing的demo 也扫描不出来啊，我debug，那个回调方法根本没走

**Comment by suedefullyi** [comment]
三星s6 edge+  扫不出来

**Comment by eversky** [comment]
我知道了，要手动调用下startspot方法，谢谢

**Comment by nwx546250** [comment]
有人解决 s6 不能扫描的问题了吗

**Comment by Ashion-AS** [comment]
实测 S7也扫不出来，换了这个库的Zbar 可以，希望解决下

**Comment by bingoogolapple** [comment]
把 qrcv_isOnlyDecodeScanBoxArea 设置成 false 试试

**Comment by laksg2009** [comment]
@bingoogolapple 按照你的这样设置[把 qrcv_isOnlyDecodeScanBoxArea 设置成 false ]我这边的三星S6已经没问题了
