### ISSUE TITLE
保存bitmap查看时全黑问题

### ISSUE THREAD

**Issue by huizaiyo** [bingoogolapple/BGAQRCode-Android#7]
对生成的bitmap保存到sdcrad成为图片，全黑

**Comment by bingoogolapple** [comment]
@huizaiyo 你保存bitmap到sdcard为图片的代码是怎样写的？

如果在demo里执行下面的代码，请添加WRITE_EXTERNAL_STORAGE权限

> 下面是我测试通过的保存生成的二维码bitmap到sdk里的代码

```java
private void saveQRCodeToSDCard(Bitmap bitmap) {
    FileOutputStream fos = null;
    try {
        File newFile = new File(Environment.getExternalStorageDirectory(), "testgenerateqrcode.png");
        if (!newFile.exists()) {
            fos = new FileOutputStream(newFile);
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, fos);
            fos.flush();

            // 通知图库更新
            sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.fromFile(newFile)));
        }
    } catch (IOException e) {
        e.printStackTrace();
    } finally {
        if (fos != null) {
            try {
                fos.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}
```

**Comment by bingoogolapple** [comment]
@huizaiyo 你那边可以了吗？

**Comment by huizaiyo** [comment]
mChineseIv.setImageBitmap(bitmap);
                saveQRCodeToSDCard(bitmap);  我现在就是直接用你的这个保存的代码 但是打开图片还是全黑

**Comment by huizaiyo** [comment]
@

**Comment by huizaiyo** [comment]
@bingoogolapple

**Comment by huizaiyo** [comment]
我用的小米 手机， 用的genymotion测试 也是黑的 @bingoogolapple

**Comment by huizaiyo** [comment]
发到电脑又是 可以看到  发现这二维码背景是透明的  只有查看的是背景是白色的才看的到。。怎么解决
按网上的解决办法 在你的QRCodeEncoder 类中 在生成二维码 时增加了  
else{
              pixels[y * size + x] = 0xffffffff;
           }

也不行
if (matrix.get(x, y)) {
                                pixels[y * size + x] = color;
                            }else{
                                pixels[y * size + x] = 0xffffffff;
                            }

**Comment by huizaiyo** [comment]
发到电脑又是 可以看到 发现这二维码背景是透明的 只有查看的是背景是白色的才看的到。。怎么解决
按网上的解决办法 在你的QRCodeEncoder 类中 在生成二维码 时增加了

else{
pixels[y * size + x] = 0xffffffff;
}

也不行
if (matrix.get(x, y)) {
pixels[y * size + x] = color;
}else{
pixels[y * size + x] = 0xffffffff;
} @bingoogolapple
