### ISSUE TITLE
我们是做快递业务的,圆通天天等快递面对手机稍稍差点的条形码基本都扫描不出来,要么就扫描很慢

### ISSUE THREAD

**Issue by liujianying** [bingoogolapple/BGAQRCode-Android#73]

**Comment by bingoogolapple** [comment]
```
/**
 * 延迟1.5秒后开始识别
 */
public void startSpot()

/**
 * 延迟delay毫秒后开始识别
 *
 * @param delay
 */
public void startSpotDelay(int delay)
```

调 startSpotDelay 方法，delay传0试试

**Comment by liushengqiang** [comment]
我试了public void startSpotDelay(int delay)这个方法，传了0，发现扫不出来，用的是小米5

**Comment by Jason-Huang-GitHub-Number** [comment]
我也试过，有的二维码识别的很慢

**Comment by tanranran** [comment]
+1
识别很慢 但是第一次识别成功后，接下来就块多了

**Comment by yufan2014** [comment]
我改了也是偶尔识别很慢，是聚焦的问题吗？微信不用那么很对齐就可以快速识别出来，但是这个不行

**Comment by liujianying** [comment]
上个版本问题还少点,这次用了最新的版本直接被吊哭, 问题很多. 主要问题是在对焦这方面上,还有和光线的强弱也有很大关系.

**Comment by kingleung10** [comment]
设置了以下两项后扫描快了很多，可以试一下

```
app:qrcv_isBarcode="false"
app:qrcv_isOnlyDecodeScanBoxArea="true"
```

**Comment by 529349029** [comment]
很慢

**Comment by 529349029** [comment]
麻烦作者看看什么原因，谢谢，扫描起来很慢!

**Comment by Swordce** [comment]
扫描确实很慢，主要是对焦上，低端机上特别明显

**Comment by AndyLeeBlue** [comment]
app:qrcv_isBarcode="false"
app:qrcv_isOnlyDecodeScanBoxArea="true"

<uses-feature android:name="android.hardware.camera"/>
<uses-feature android:name="android.hardware.camera.autofocus"/>

如上设置快很多，和微信差不多快

**Comment by Hootoo** [comment]
我试过delay传0，MX4没问题 很快。请问这里startSpotDelay(1500)是有什么特别的原因吗？是不是会有部分机型会有问题，必须delay>0？

**Comment by bingoogolapple** [comment]
参考 #170
