### ISSUE TITLE
扫描界面onCreate中申请权限，允许后无法预览

### ISSUE THREAD

**Issue by qinyang1018** [bingoogolapple/BGAQRCode-Android#74]
在扫描界面onCreate中申请权限，允许后无法预览，应该是QRCodeView生命周期问题，不知道该如何解决

**Comment by qinyang1018** [comment]
已经解决，在允许权限回调中动态去addview    这样就可以了

**Comment by zhengwuhao** [comment]
@qinyang1018 请问是怎么解决的？

**Comment by qinyang1018** [comment]
@zhengwuhao  权限申请成功后动态添加扫描的view
