### ISSUE TITLE
Moto X Pro 扫描预览界面，二维码被压缩

### ISSUE THREAD

**Issue by Saxxhw** [bingoogolapple/BGAQRCode-Android#75]
宽屏手机的二维码预览中显示的图像是被压缩的，二维码被挤扁了，正方形的二维码在手机上显示的却是长方形的。。大神能解决下吗。。

**Comment by bingoogolapple** [comment]
[参考 README 里的常见问题1](https://github.com/bingoogolapple/BGAQRCode-Android)
