### ISSUE TITLE
界面设置成横屏，条码扫描不了了。

### ISSUE THREAD

**Issue by HSUMMERBIRDL** [bingoogolapple/BGAQRCode-Android#78]
我并不是在这个项目中设置成横屏，而是一个demo集成了条码扫描功能，竖屏的时候是可以的，但是界面设置成横屏后去扫描不出来，我四个方位去扫描都试过了，都扫描不出来。用的是zxing。

**Comment by bingoogolapple** [comment]
用 v1.1.8 版本
