### ISSUE TITLE
生成的bitmap  直接解析报com.google.zxing.NotFoundException... 问题

### ISSUE THREAD

**Issue by louisgeek** [bingoogolapple/BGAQRCode-Android#8]
![qq 20160418201254](https://cloud.githubusercontent.com/assets/7745173/14603753/2edc4728-05a2-11e6-8bea-1c700cedc540.png)
![qq 20160418201319](https://cloud.githubusercontent.com/assets/7745173/14603759/36bec5ba-05a2-11e6-8080-d0dfe1972762.png)
![image](https://cloud.githubusercontent.com/assets/7745173/14603771/428bf1ce-05a2-11e6-9709-1a845258cea1.png)

**Comment by bingoogolapple** [comment]
@louisgeek 谢谢反馈，这个问题之前我也遇到了，一直没想到解决方案，后来@huizaiyo 提了issues #7 ，把你们俩提的问题综合起来就解决了。

我晚上重新提个新版本

**Comment by louisgeek** [comment]
大神 请收下我的膝盖，佩服啊，要是能进阶到你这么厉害就好了

**Comment by huizaiyo** [comment]
还有个情况，这个扫描，好像整个屏幕都可以扫，并不是只有扫描框可以扫，感觉怪怪的。大神有时间再来个打开本地相册选择二维码图片扫描就好了。

**Comment by bingoogolapple** [comment]
@louisgeek 是你提醒了我哈

**Comment by bingoogolapple** [comment]
@huizaiyo 打开本地相册选择二维码图片扫描这个已经实现了哈，只是需要你自己从相册选择图片，拿到图片路径后通过BitmapFactory.decodeFile()获取Bitmap，然后调用下面的方法

```Java
        QRCodeDecoder.decodeQRCode(bitmap, new QRCodeDecoder.Delegate() {
            @Override
            public void onDecodeQRCodeSuccess(String result) {
                Toast.makeText(Generatectivity.this, result, Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onDecodeQRCodeFailure() {
                Toast.makeText(Generatectivity.this, errorTip, Toast.LENGTH_SHORT).show();
            }
        });
```
只有扫描框可以扫这个以后再看时间。
