### ISSUE TITLE
startSpot()在MX4上报错

### ISSUE THREAD

**Issue by KingJames6** [bingoogolapple/BGAQRCode-Android#82]
startCamera();
        // 开始前先移除之前的任务
        mHandler.removeCallbacks(mOneShotPreviewCallbackTask);
        mHandler.postDelayed(mOneShotPreviewCallbackTask, delay);

魅族MX4使用startSpot()就是默认的delay1500ms会报错 Camera is being used after Camera.release()
是不是应该在startCamera之前移除任务？

**Comment by huangyaozhong** [comment]
这个问题你是怎么解决的？
