### ISSUE TITLE
我想问一下，之前生成二维码是有回调的，更新了1.1.4之后好像没有回调了？

### ISSUE THREAD

**Issue by rehan91** [bingoogolapple/BGAQRCode-Android#83]
/**
 * 同步创建指定前景色、白色背景色、带logo的二维码图片。该方法是耗时操作，请在子线程中调用。
 *
 * @param content         要生成的二维码图片内容
 * @param size            图片宽高，单位为px
 * @param foregroundColor 二维码图片的前景色
 * @param logo            二维码图片的logo
 */
public static Bitmap syncEncodeQRCode(String content, int size, int foregroundColor, Bitmap logo)
现在没有回调的话，如何知道成功或者失败呢？如何拿到生成的二维码图像呢？

**Comment by bingoogolapple** [comment]
现在是同步的，直接就返回了，需要你自己在子线程里操作
