### ISSUE TITLE
请求相机权限的bug

### ISSUE THREAD

**Issue by Swordce** [bingoogolapple/BGAQRCode-Android#84]
以zxingDemo为例：
请求权限--->点击返回键（即不允许也不禁止）--->进入扫描界面--->点击开始识别--->crash

crash信息：
![image](https://cloud.githubusercontent.com/assets/16829238/20424953/4cfe238e-adb3-11e6-8d0d-b4a3bca05e42.png)

还有长时间没选择权限选项，屏幕会黑屏

**Comment by Tonygf** [comment]
也不允许，也不禁止，不就是代表禁止了吗
