### ISSUE TITLE
yuv图像的旋转问题

### ISSUE THREAD

**Issue by zhouweihui** [bingoogolapple/BGAQRCode-Android#88]
byte[] rotatedData = new byte[mData.length];

 for (int y = 0; y < height; y++) {

       for (int x = 0; x < width; x++) {

           rotatedData[x * height + height - y - 1] = mData[x + y * width];

       }
 }

这段代码是对yuv图像做旋转的吗，但我把rotatedData保存成本地图片，发现图片的整体颜色都变绿的。

**Comment by eywalink** [comment]
因为data本身就不是 rgb
[http://blog.csdn.net/yanzi1225627/article/details/8626411](url)
是yuv420sp

**Comment by bingoogolapple** [comment]
用最新版
