### ISSUE TITLE
依赖传递写法

### ISSUE THREAD

**Issue by Tconan99** [bingoogolapple/BGAQRCode-Android#89]
![image](https://cloud.githubusercontent.com/assets/13305703/20785865/7a3e5948-b7dd-11e6-95ce-8e931779ebb7.png)

能否把Module zxing里面的依赖 
```
compile project(':qrcodecore') 
```
改成 
```
compile 'cn.bingoogolapple:bga-qrcodecore:1.1.5'
```

现在的依赖写法是
```
compile 'com.google.zxing:core:3.2.1'
compile 'cn.bingoogolapple:bga-qrcodecore:latestVersion@aar'
compile 'cn.bingoogolapple:bga-zxing:latestVersion@aar'
```
因为写了@aar 就不能依赖传递了，所以在多级aar依赖时这么写非常麻烦, 改完写法之后
```
compile "com.jc.android:bga-zxing:1.1.5"
```
这么写就可以, 因为这么写可以依赖传递, 多级aar依赖也不用重复写了

**Comment by bingoogolapple** [comment]
现在不会，以后也不会改。。。。。
