### ISSUE TITLE
非白色背景的二维码扫描结果出不了，

### ISSUE THREAD

**Issue by Seancss** [bingoogolapple/BGAQRCode-Android#91]
# 图片地址在下面链接， 不是白色背景，ZBar和ZXing扫描都无效，麻烦看下，谢谢 
# [未识别二维码地址](http://upload-images.jianshu.io/upload_images/1744889-29ec2fa306b68a2f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by haimingpku** [comment]
我遇到同样的问题，现在如果是非白色的背景，也是识别不来。

**Comment by csschn** [comment]
最后和客户商量了 ，改成白色背景的二维码。
